param(
    [string]$Python = "python",
    [string]$VenvDir,
    [switch]$InstallDevDependencies,
    [switch]$UseActivePython,
    [switch]$IfNeeded,
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

function Get-ProjectRoot {
    if ($PSScriptRoot) {
        return (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
    }
    return (Get-Location).Path
}

function Get-DotEnvValue {
    param(
        [string]$FilePath,
        [string]$Key
    )

    if (-not (Test-Path -LiteralPath $FilePath)) {
        return $null
    }

    foreach ($line in Get-Content -LiteralPath $FilePath) {
        $trimmed = $line.Trim()
        if (-not $trimmed -or $trimmed.StartsWith("#")) {
            continue
        }

        $parts = $trimmed -split "=", 2
        if ($parts.Count -eq 2 -and $parts[0].Trim() -eq $Key) {
            return $parts[1].Trim()
        }
    }

    return $null
}

function Get-PythonVersionText {
    param(
        [string]$PythonExe
    )

    $versionText = & $PythonExe -c "import sys; print('.'.join(str(part) for part in sys.version_info[:3]))"
    if ($LASTEXITCODE -ne 0) {
        throw "Python executable '$PythonExe' was not found or failed to run."
    }
    return ($versionText | Select-Object -First 1).Trim()
}

function Test-CondaEnvironmentActive {
    return -not [string]::IsNullOrWhiteSpace($env:CONDA_PREFIX)
}

function Test-VirtualEnvironmentActive {
    return -not [string]::IsNullOrWhiteSpace($env:VIRTUAL_ENV)
}

function Get-PythonExecutablePath {
    param(
        [string]$PythonExe
    )

    $resolvedPath = & $PythonExe -c "import sys; print(sys.executable)"
    if ($LASTEXITCODE -ne 0) {
        throw "Python executable '$PythonExe' was not found or failed to run."
    }
    return ($resolvedPath | Select-Object -First 1).Trim()
}

function Get-FileMtimeToken {
    param(
        [string]$PythonExe,
        [string]$TargetFile
    )

    $mtimeValue = & $PythonExe -c "import os, sys; print(int(os.path.getmtime(sys.argv[1])))" $TargetFile
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to read file timestamp for $TargetFile."
    }
    return ($mtimeValue | Select-Object -First 1).Trim()
}

function Test-BackendImportsAvailable {
    param(
        [string]$PythonExe,
        [bool]$RequireDevDependencies
    )

    $requireDevFlag = if ($RequireDevDependencies) { "true" } else { "false" }
    $pythonCheckCode = "import importlib.util, sys; required = ['fastapi', 'uvicorn', 'deepagents_template']; required.extend(['pytest', 'ruff']) if sys.argv[1].lower() == 'true' else None; missing = [name for name in required if importlib.util.find_spec(name) is None]; raise SystemExit(0 if not missing else 1)"
    & $PythonExe -c $pythonCheckCode $requireDevFlag | Out-Null

    return $LASTEXITCODE -eq 0
}

function Write-BootstrapState {
    param(
        [string]$FilePath,
        [string]$InterpreterPath,
        [bool]$HasDevDependencies,
        [string]$PyProjectMtimeToken
    )

    $content = @(
        "# Generated by quick-start/bootstrap.ps1"
        "BOOTSTRAP_INTERPRETER=$InterpreterPath"
        "BOOTSTRAP_DEV_DEPENDENCIES=$(if ($HasDevDependencies) { 'true' } else { 'false' })"
        "BOOTSTRAP_PYPROJECT_MTIME=$PyProjectMtimeToken"
    )

    Set-Content -LiteralPath $FilePath -Value $content -Encoding ASCII
}

function Get-EnvironmentSummary {
    param(
        [bool]$UseActivatedPythonMode,
        [string]$InterpreterPath,
        [string]$VenvPath
    )

    $virtualEnv = $env:VIRTUAL_ENV
    $condaEnv = $env:CONDA_PREFIX

    if (-not [string]::IsNullOrWhiteSpace($virtualEnv) -and -not [string]::IsNullOrWhiteSpace($condaEnv)) {
        return "Virtualenv ($virtualEnv) on top of Conda ($condaEnv)"
    }
    if (-not [string]::IsNullOrWhiteSpace($virtualEnv)) {
        return "Virtualenv ($virtualEnv)"
    }
    if (-not [string]::IsNullOrWhiteSpace($condaEnv)) {
        return "Conda ($condaEnv)"
    }
    if ($UseActivatedPythonMode) {
        return "Active Python ($InterpreterPath)"
    }
    return ".venv fallback ($VenvPath)"
}

function Show-BootstrapSummary {
    param(
        [string]$EnvironmentSummary,
        [string]$InterpreterPath,
        [string]$BootstrapMode,
        [bool]$RequireDevDependencies
    )

    if ($Quiet) {
        return
    }

    Write-Host "Bootstrap summary"
    Write-Host "  Environment: $EnvironmentSummary"
    Write-Host "  Python executable: $InterpreterPath"
    Write-Host "  Bootstrap mode: $BootstrapMode"
    Write-Host "  Dev dependencies required: $(if ($RequireDevDependencies) { 'yes' } else { 'no' })"
}

$ProjectRoot = Get-ProjectRoot
if ([string]::IsNullOrWhiteSpace($VenvDir)) {
    $VenvDir = Join-Path $ProjectRoot ".venv"
}

$EnvFile = Join-Path $ProjectRoot ".env"
$EnvExampleFile = Join-Path $ProjectRoot ".env.example"
$PyProjectFile = Join-Path $ProjectRoot "pyproject.toml"
$BootstrapStateFile = Join-Path $ProjectRoot ".bootstrap_backend_state.env"

Push-Location $ProjectRoot
try {
    $UseActivatedPython = $UseActivePython.IsPresent -or (Test-VirtualEnvironmentActive) -or (Test-CondaEnvironmentActive)
    $BootstrapPython = $Python
    if ($UseActivatedPython) {
        $BootstrapPython = Get-PythonExecutablePath -PythonExe $Python
    }

    $pythonVersionText = Get-PythonVersionText -PythonExe $BootstrapPython
    if ([version]$pythonVersionText -lt [version]"3.11.0") {
        throw "Python 3.11 or newer is required. Detected version: $pythonVersionText . Please activate a newer environment or use a newer Python interpreter."
    }

    if ($UseActivatedPython) {
        $InstallPython = $BootstrapPython
    } else {
        if (-not (Test-Path -LiteralPath $VenvDir)) {
            if (-not $Quiet) {
                Write-Host "Creating virtual environment at $VenvDir ..."
            }
            & $Python -m venv $VenvDir
            if ($LASTEXITCODE -ne 0) {
                throw "Virtual environment creation failed with exit code $LASTEXITCODE. You can also activate a Conda or virtualenv environment first and rerun bootstrap."
            }
        }

        $InstallPython = Join-Path $VenvDir "Scripts\python.exe"
        if (-not (Test-Path -LiteralPath $InstallPython)) {
            throw "Virtual environment Python not found at $InstallPython . Delete the broken .venv and rerun bootstrap, or activate an environment first."
        }
    }

    $RequireDevDependencies = $InstallDevDependencies.IsPresent
    $BootstrapMode = if ($IfNeeded) { "if-needed" } else { "always" }
    if (-not $Quiet) {
        Write-Host "Project root: $ProjectRoot"
        Show-BootstrapSummary -EnvironmentSummary (Get-EnvironmentSummary -UseActivatedPythonMode $UseActivatedPython -InterpreterPath $InstallPython -VenvPath $VenvDir) -InterpreterPath $InstallPython -BootstrapMode $BootstrapMode -RequireDevDependencies $RequireDevDependencies
        Write-Host "Detected Python: $pythonVersionText"
    }

    $ImportsAvailable = Test-BackendImportsAvailable -PythonExe $InstallPython -RequireDevDependencies $RequireDevDependencies
    $PyProjectMtimeToken = Get-FileMtimeToken -PythonExe $InstallPython -TargetFile $PyProjectFile
    $BootstrapReason = $null

    if ($IfNeeded) {
        if (-not $ImportsAvailable) {
            $BootstrapReason = "required Python packages are missing"
        } elseif (Test-Path -LiteralPath $BootstrapStateFile) {
            $StateInterpreter = Get-DotEnvValue -FilePath $BootstrapStateFile -Key "BOOTSTRAP_INTERPRETER"
            $StateDevDependencies = Get-DotEnvValue -FilePath $BootstrapStateFile -Key "BOOTSTRAP_DEV_DEPENDENCIES"
            $StatePyProjectMtime = Get-DotEnvValue -FilePath $BootstrapStateFile -Key "BOOTSTRAP_PYPROJECT_MTIME"

            if ($StateInterpreter -ne $InstallPython) {
                $BootstrapReason = "Python interpreter changed since the last bootstrap"
            } elseif ($RequireDevDependencies -and $StateDevDependencies -ne "true") {
                $BootstrapReason = "development dependencies are now required"
            } elseif ($StatePyProjectMtime -ne $PyProjectMtimeToken) {
                $BootstrapReason = "pyproject.toml changed since the last bootstrap"
            }
        } else {
            Write-BootstrapState -FilePath $BootstrapStateFile -InterpreterPath $InstallPython -HasDevDependencies $RequireDevDependencies -PyProjectMtimeToken $PyProjectMtimeToken
            if (-not $Quiet) {
                Write-Host "Bootstrap already satisfied. Backfilled bootstrap state metadata."
            }
        }
    } else {
        $BootstrapReason = "bootstrap mode is set to always"
    }

    if ($BootstrapReason) {
        if (-not $Quiet) {
            Write-Host "Bootstrap action: $BootstrapReason."
            Write-Host "Upgrading pip..."
        }
        & $InstallPython -m pip install --upgrade pip --disable-pip-version-check --progress-bar off
        if ($LASTEXITCODE -ne 0) {
            throw "pip upgrade failed with exit code $LASTEXITCODE. Check network access and Python packaging configuration."
        }

        if ($RequireDevDependencies) {
            if (-not $Quiet) {
                Write-Host "Installing project in editable mode with development dependencies..."
            }
            & $InstallPython -m pip install -e ".[dev]" --disable-pip-version-check --progress-bar off
        } else {
            if (-not $Quiet) {
                Write-Host "Installing project in editable mode..."
            }
            & $InstallPython -m pip install -e $ProjectRoot --disable-pip-version-check --progress-bar off
        }
        if ($LASTEXITCODE -ne 0) {
            throw "Editable install failed with exit code $LASTEXITCODE. Check dependency download access and your Python environment."
        }

        Write-BootstrapState -FilePath $BootstrapStateFile -InterpreterPath $InstallPython -HasDevDependencies $RequireDevDependencies -PyProjectMtimeToken $PyProjectMtimeToken
        if (-not $Quiet) {
            Write-Host "Bootstrap completed."
        }
    } elseif (-not $Quiet) {
        Write-Host "Bootstrap already satisfied. Skipping pip upgrade and editable install."
    }

    if (-not (Test-Path -LiteralPath $EnvFile) -and (Test-Path -LiteralPath $EnvExampleFile)) {
        Copy-Item -LiteralPath $EnvExampleFile -Destination $EnvFile
        if (-not $Quiet) {
            Write-Host "Created $EnvFile from .env.example"
            Write-Host "Please edit .env before starting the first real model-backed conversion."
        }
    }
}
finally {
    Pop-Location
}
