#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PYTHON_BIN="${PYTHON_BIN:-python3}"
VENV_DIR="${VENV_DIR:-${PROJECT_ROOT}/.venv}"
ENV_FILE="${PROJECT_ROOT}/.env"
ENV_EXAMPLE_FILE="${PROJECT_ROOT}/.env.example"
INSTALL_DEV_DEPENDENCIES="${INSTALL_DEV_DEPENDENCIES:-false}"
USE_ACTIVE_PYTHON="${USE_ACTIVE_PYTHON:-false}"
BOOTSTRAP_IF_NEEDED="${BOOTSTRAP_IF_NEEDED:-false}"
BOOTSTRAP_QUIET="${BOOTSTRAP_QUIET:-false}"
BOOTSTRAP_STATE_FILE="${PROJECT_ROOT}/.bootstrap_backend_state.env"
PYPROJECT_FILE="${PROJECT_ROOT}/pyproject.toml"

read_dotenv_value() {
  local key="$1"
  local file="$2"

  [[ -f "${file}" ]] || return 1

  awk -F '=' -v target="${key}" '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }
    {
      current=$1
      gsub(/^[[:space:]]+|[[:space:]]+$/, "", current)
      if (current == target) {
        value=substr($0, index($0, "=") + 1)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
        print value
        exit
      }
    }
  ' "${file}"
}

test_virtualenv_active() {
  [[ -n "${VIRTUAL_ENV:-}" ]]
}

test_conda_environment_active() {
  [[ -n "${CONDA_PREFIX:-}" ]]
}

get_python_version_text() {
  local python_exe="$1"
  "${python_exe}" -c 'import sys; print(".".join(str(part) for part in sys.version_info[:3]))'
}

get_python_executable_path() {
  local python_exe="$1"
  "${python_exe}" -c 'import sys; print(sys.executable)'
}

get_file_mtime_token() {
  local python_exe="$1"
  local target_file="$2"
  "${python_exe}" -c 'import os, sys; print(int(os.path.getmtime(sys.argv[1])))' "${target_file}"
}

test_backend_imports_available() {
  local python_exe="$1"
  local require_dev="$2"

  "${python_exe}" -c '
import importlib.util
import sys

required = ["fastapi", "uvicorn", "deepagents_template"]
if sys.argv[1].lower() == "true":
    required.extend(["pytest", "ruff"])

missing = [name for name in required if importlib.util.find_spec(name) is None]
raise SystemExit(0 if not missing else 1)
' "${require_dev}" >/dev/null 2>&1
}

write_bootstrap_state() {
  local interpreter_path="$1"
  local has_dev_dependencies="$2"
  local pyproject_mtime="$3"

  cat >"${BOOTSTRAP_STATE_FILE}" <<EOF
# Generated by quick-start/bootstrap.sh
BOOTSTRAP_INTERPRETER=${interpreter_path}
BOOTSTRAP_DEV_DEPENDENCIES=${has_dev_dependencies}
BOOTSTRAP_PYPROJECT_MTIME=${pyproject_mtime}
EOF
}

get_environment_summary() {
  local interpreter_path="$1"

  if [[ -n "${VIRTUAL_ENV:-}" && -n "${CONDA_PREFIX:-}" ]]; then
    printf 'Virtualenv (%s) on top of Conda (%s)\n' "${VIRTUAL_ENV}" "${CONDA_PREFIX}"
    return 0
  fi
  if [[ -n "${VIRTUAL_ENV:-}" ]]; then
    printf 'Virtualenv (%s)\n' "${VIRTUAL_ENV}"
    return 0
  fi
  if [[ -n "${CONDA_PREFIX:-}" ]]; then
    printf 'Conda (%s)\n' "${CONDA_PREFIX}"
    return 0
  fi
  if [[ "${USE_ACTIVATED_PYTHON}" == "true" ]]; then
    printf 'Active Python (%s)\n' "${interpreter_path}"
    return 0
  fi
  printf '.venv fallback (%s)\n' "${VENV_DIR}"
}

if ! command -v "${PYTHON_BIN}" >/dev/null 2>&1; then
  echo "Error: ${PYTHON_BIN} not found." >&2
  echo "Tip: run with PYTHON_BIN=python ./bootstrap.sh if your system uses 'python'." >&2
  exit 1
fi

USE_ACTIVATED_PYTHON="false"
if [[ "${USE_ACTIVE_PYTHON}" == "true" ]] || test_virtualenv_active || test_conda_environment_active; then
  USE_ACTIVATED_PYTHON="true"
fi

BOOTSTRAP_PYTHON="${PYTHON_BIN}"
if [[ "${USE_ACTIVATED_PYTHON}" == "true" ]]; then
  BOOTSTRAP_PYTHON="$(get_python_executable_path "${PYTHON_BIN}")"
fi

PYTHON_VERSION="$(get_python_version_text "${BOOTSTRAP_PYTHON}")"
if ! "${BOOTSTRAP_PYTHON}" -c 'import sys; raise SystemExit(0 if sys.version_info >= (3, 11) else 1)'; then
  echo "Error: Python 3.11 or newer is required. Detected version: ${PYTHON_VERSION}" >&2
  echo "Tip: activate a newer environment or choose a newer interpreter with PYTHON_BIN." >&2
  exit 1
fi

if [[ "${USE_ACTIVATED_PYTHON}" == "true" ]]; then
  INSTALL_PYTHON="${BOOTSTRAP_PYTHON}"
else
  if [[ ! -d "${VENV_DIR}" ]]; then
    if [[ "${BOOTSTRAP_QUIET}" != "true" ]]; then
      echo "Creating virtual environment at ${VENV_DIR} ..."
    fi
    "${PYTHON_BIN}" -m venv "${VENV_DIR}" || {
      echo "Error: virtual environment creation failed. Activate a Conda or virtualenv environment first or inspect your Python installation." >&2
      exit 1
    }
  fi
  INSTALL_PYTHON="${VENV_DIR}/bin/python"
fi

BOOTSTRAP_MODE="always"
if [[ "${BOOTSTRAP_IF_NEEDED}" == "true" ]]; then
  BOOTSTRAP_MODE="if-needed"
fi

if [[ "${BOOTSTRAP_QUIET}" != "true" ]]; then
  echo "Project root: ${PROJECT_ROOT}"
  echo "Bootstrap summary"
  echo "  Environment: $(get_environment_summary "${INSTALL_PYTHON}")"
  echo "  Python executable: ${INSTALL_PYTHON}"
  echo "  Bootstrap mode: ${BOOTSTRAP_MODE}"
  echo "  Dev dependencies required: $(if [[ "${INSTALL_DEV_DEPENDENCIES}" == "true" ]]; then printf 'yes'; else printf 'no'; fi)"
  echo "Detected Python: ${PYTHON_VERSION}"
fi

IMPORTS_AVAILABLE="false"
if test_backend_imports_available "${INSTALL_PYTHON}" "${INSTALL_DEV_DEPENDENCIES}"; then
  IMPORTS_AVAILABLE="true"
fi

PYPROJECT_MTIME="$(get_file_mtime_token "${INSTALL_PYTHON}" "${PYPROJECT_FILE}")"
BOOTSTRAP_REASON=""

if [[ "${BOOTSTRAP_IF_NEEDED}" == "true" ]]; then
  if [[ "${IMPORTS_AVAILABLE}" != "true" ]]; then
    BOOTSTRAP_REASON="required Python packages are missing"
  elif [[ -f "${BOOTSTRAP_STATE_FILE}" ]]; then
    STATE_INTERPRETER="$(read_dotenv_value "BOOTSTRAP_INTERPRETER" "${BOOTSTRAP_STATE_FILE}" || true)"
    STATE_DEV_DEPENDENCIES="$(read_dotenv_value "BOOTSTRAP_DEV_DEPENDENCIES" "${BOOTSTRAP_STATE_FILE}" || true)"
    STATE_PYPROJECT_MTIME="$(read_dotenv_value "BOOTSTRAP_PYPROJECT_MTIME" "${BOOTSTRAP_STATE_FILE}" || true)"

    if [[ "${STATE_INTERPRETER}" != "${INSTALL_PYTHON}" ]]; then
      BOOTSTRAP_REASON="Python interpreter changed since the last bootstrap"
    elif [[ "${INSTALL_DEV_DEPENDENCIES}" == "true" && "${STATE_DEV_DEPENDENCIES}" != "true" ]]; then
      BOOTSTRAP_REASON="development dependencies are now required"
    elif [[ "${STATE_PYPROJECT_MTIME}" != "${PYPROJECT_MTIME}" ]]; then
      BOOTSTRAP_REASON="pyproject.toml changed since the last bootstrap"
    fi
  else
    write_bootstrap_state "${INSTALL_PYTHON}" "${INSTALL_DEV_DEPENDENCIES}" "${PYPROJECT_MTIME}"
    if [[ "${BOOTSTRAP_QUIET}" != "true" ]]; then
      echo "Bootstrap already satisfied. Backfilled bootstrap state metadata."
    fi
  fi
else
  BOOTSTRAP_REASON="bootstrap mode is set to always"
fi

if [[ -n "${BOOTSTRAP_REASON}" ]]; then
  if [[ "${BOOTSTRAP_QUIET}" != "true" ]]; then
    echo "Bootstrap action: ${BOOTSTRAP_REASON}."
    echo "Upgrading pip..."
  fi
  "${INSTALL_PYTHON}" -m pip install --upgrade pip --disable-pip-version-check --progress-bar off || {
    echo "Error: pip upgrade failed. Check network access and Python packaging configuration." >&2
    exit 1
  }

  if [[ "${INSTALL_DEV_DEPENDENCIES}" == "true" ]]; then
    if [[ "${BOOTSTRAP_QUIET}" != "true" ]]; then
      echo "Installing project in editable mode with development dependencies..."
    fi
    "${INSTALL_PYTHON}" -m pip install -e ".[dev]" --disable-pip-version-check --progress-bar off || {
      echo "Error: editable install with dev dependencies failed. Check dependency download access and your Python environment." >&2
      exit 1
    }
  else
    if [[ "${BOOTSTRAP_QUIET}" != "true" ]]; then
      echo "Installing project in editable mode..."
    fi
    "${INSTALL_PYTHON}" -m pip install -e "${PROJECT_ROOT}" --disable-pip-version-check --progress-bar off || {
      echo "Error: editable install failed. Check dependency download access and your Python environment." >&2
      exit 1
    }
  fi

  write_bootstrap_state "${INSTALL_PYTHON}" "${INSTALL_DEV_DEPENDENCIES}" "${PYPROJECT_MTIME}"
  if [[ "${BOOTSTRAP_QUIET}" != "true" ]]; then
    echo "Bootstrap completed."
  fi
elif [[ "${BOOTSTRAP_QUIET}" != "true" ]]; then
  echo "Bootstrap already satisfied. Skipping pip upgrade and editable install."
fi

if [[ ! -f "${ENV_FILE}" && -f "${ENV_EXAMPLE_FILE}" ]]; then
  cp "${ENV_EXAMPLE_FILE}" "${ENV_FILE}"
  if [[ "${BOOTSTRAP_QUIET}" != "true" ]]; then
    echo "Created ${ENV_FILE} from .env.example"
    echo "Please edit .env before starting the first real model-backed conversion."
  fi
fi
